apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag
data:
  OLLAMA_BASE_URL: "http://host.docker.internal:11434"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mousike"
  DOCLING_BASE_URL: "http://docling-service:5001"
  PHOENIX_OTLP_GRPC_URL: "http://phoenix-service:4317"
  GRAFANA_OTLP_HTTP_URL: "http://grafana-lgtm-service:4318"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DOCUMENT_SERVICE_URL: "http://document-service:8090"
  SPRING_PROFILES_ACTIVE: "k8s"
